//
//  enums.h
//  ike-tdgame
//
//  Created by Like Zhang on 12/17/12.
//
//

#ifndef __ike_tdgame__enums__
#define __ike_tdgame__enums__

#include <iostream>

enum ENUM_MOVE_DIRECTION
{
    ENUM_MOVE_DIRECTION_NONE = 0,
    ENUM_MOVE_DIRECTION_UP,
    ENUM_MOVE_DIRECTION_DOWN,
    ENUM_MOVE_DIRECTION_LEFT,
    ENUM_MOVE_DIRECTION_RIGHT
};

enum ENUM_ELEMENT_CLASS_TYPE
{
    Metal = 1,
    Wood = 2,
    Earth = 3,
    Water = 4,
    Fire = 5,
    Special = 6,
};

enum ENUM_ITEM_TYPE
{
    STONE = 1
    
};

enum ENUM_DAMAGE_TYPE
{
    ENUM_DAMAGE_SINGLE_ENEMY,
    ENUM_DAMAGE_SINGLE_TILE,
    ENUM_DAMAGE_SQUARE_TILES,
    ENUM_DAMAGE_CROSS_TILES,
    ENUM_DAMAGE_ROUND_AREA,
    ENUM_DAMAGE_BURNING_FIRE,
};

enum ENUM_BUILDING_ATTACK_TYPE
{
    ENUM_BUILDING_ATTACK_NONE,
    ENUM_BUILDING_ATTACK_SINGLE_ARROW,
    ENUM_BUILDING_ATTACK_FIREGUN,
    ENUM_BUILDING_ATTACK_THROW_STONE,
    ENUM_BUILDING_ATTACK_CANNON,
    ENUM_BUILDING_ATTACK_ROUND,
    ENUM_BUILDING_ATTACK_MULTI_ARROW,
    ENUM_BUILDING_ATTACK_SHOTGUN,
    ENUM_BUILDING_ATTACK_MUD,
    ENUM_BUILDING_ATTACK_POISON,
    ENUM_BUILDING_ATTACK_SNIPER,
    ENUM_BUILDING_ATTACK_MACHINEGUN,
    ENUM_BUILDING_ATTACK_ROCKET,
    ENUM_BUILDING_ATTACK_BASE,
};

enum ENUM_ENEMY_ATTACK_TYPE
{
    ENUM_ENEMY_ATTACK_MELEE,
    ENUM_ENEMY_ATTACK_THROW_STONE,
    ENUM_ENEMY_ATTACK_THROW_SPEAR,
    ENUM_ENEMY_ATTACK_ARROW,
    ENUM_ENEMY_ATTACK_HALF_CIRCLE_MELEE,
    ENUM_ENEMY_ATTACK_ROUND_AREA,
    ENUM_ENEMY_ATTACK_SNAKE_VENOM,
    ENUM_ENEMY_ATTACK_SPIDER_WEB,
    ENUM_ENEMY_ATTACK_SHOCK_WAVE,
};

enum ENUM_BULLET_ANIMATION
{
    ENUM_BULLET_ANIMATION_STONE,
    ENUM_BULLET_ANIMATION_FIRE_STONE,
    ENUM_BULLET_ANIMATION_ROCK,
    
    ENUM_BULLET_ANIMATION_ARROW,
    ENUM_BULLET_ANIMATION_FIRE_ARROW,

    ENUM_BULLET_ANIMATION_SPEAR,
    
    ENUM_BULLET_ANIMATION_FIREGUN_BULLET,
    ENUM_BULLET_ANIMATION_ROCKET,
    ENUM_BULLET_ANIMATION_SNAKE_VENOM,
    ENUM_BULLET_ANIMATION_SPIDER_WEB,
    ENUM_BULLET_ANIMATION_SNIPER_FIRE,
    
};

enum ENUM_TARGET_TYPE
{
    ATTACK_TARGET_NONE,
    ATTACK_TARGET_ENEMY,
    ATTACK_TARGET_BUILDING,
};

enum ENUM_TEAM
{
    ENUM_TEAM_NONE = 0,
    ENUM_TEAM_COMPUTER = 1,
    ENUM_TEAM_PLAYER = 2,
};

enum ENUM_TILE_DIRECTION
{
    TileNone,
    TileHorizontal,
    TileVertical,
    TileLeftTop,
    TileLeftBottom,
    TileRightTop,
    TileRightBottom,
};

enum ENUM_ROAD_DIRECTION
{
    RoadNone = 0,
    RoadUp = 1,
    RoadDown = 2,
    RoadLeft = 4,
    RoadRight = 8,
};

enum ENUM_NPC_ANIMATION
{
    ENUM_NPC_ANIMATION_NONE,
    ENUM_NPC_ANIMATION_MOVING_UP,
    ENUM_NPC_ANIMATION_MOVING_DOWN,
    ENUM_NPC_ANIMATION_MOVING_LEFT,
    ENUM_NPC_ANIMATION_MOVING_RIGHT,
    ENUM_NPC_ANIMATION_ATTACK_RIGHT,
    ENUM_NPC_ANIMATION_ATTACK_TOPRIGHT,
    ENUM_NPC_ANIMATION_ATTACK_TOP,
    ENUM_NPC_ANIMATION_ATTACK_TOPLEFT,
    ENUM_NPC_ANIMATION_ATTACK_LEFT,
    ENUM_NPC_ANIMATION_ATTACK_LEFTBOTTOM,
    ENUM_NPC_ANIMATION_ATTACK_BOTTOM,
    ENUM_NPC_ANIMATION_ATTACK_RIGHTBOTTOM,
    ENUM_NPC_ANIMATION_STAND_UP,
    ENUM_NPC_ANIMATION_STAND_DOWN,
    ENUM_NPC_ANIMATION_STAND_LEFT,
    ENUM_NPC_ANIMATION_STAND_RIGHT,
    ENUM_NPC_ANIMATION_DEAD_UP,
    ENUM_NPC_ANIMATION_DEAD_DOWN,
    ENUM_NPC_ANIMATION_DEAD_LEFT,
    ENUM_NPC_ANIMATION_DEAD_RIGHT,

    // for special skill
    ENUM_NPC_ANIMATION_USE_SKILL_1_UP,
    ENUM_NPC_ANIMATION_USE_SKILL_1_DOWN,
    ENUM_NPC_ANIMATION_USE_SKILL_1_LEFT,
    ENUM_NPC_ANIMATION_USE_SKILL_1_RIGHT,
    
    ENUM_NPC_ANIMATION_USE_SKILL_2_UP,
    ENUM_NPC_ANIMATION_USE_SKILL_2_DOWN,
    ENUM_NPC_ANIMATION_USE_SKILL_2_LEFT,
    ENUM_NPC_ANIMATION_USE_SKILL_2_RIGHT,

    
};

enum ENUM_BUILDING_DIRECTION
{
    BUILDING_DIRECTION_UNKNOWN,
    BUILDING_DIRECTION_UP,
    BUILDING_DIRECTION_DOWN,
    BUILDING_DIRECTION_LEFT,
    BUILDING_DIRECTION_RIGHT
};

enum ENUM_BUILDING_TYPE
{
    ENUM_BUILDING_SPECIAL,
    ENUM_WEAPON_MISSLE,
    ENUM_WEAPON_SNIPE,
    ENUM_WEAPON_SHOT,
    ENUM_BUILDING_ASSIST,
    ENUM_BUILDING_TYPE_LAST
};

enum ENUM_PROGRESS_FLAG
{
    ENUM_FIRST_TIME_MOVE_PLAYER = 1,
    ENUM_FIRST_TIME_ON_STAGE = 2,
    ENUM_FIRST_TIME_PLACE_SNIPE_WEAPON = 4,
    ENUM_FIRST_TIME_PLACE_MISSLE_WEAPON = 8,
    ENUM_COMPLETE_BASIC_TUTORIAL = 16,
    ENUM_FIRST_TIME_UPGRADE_WEAPON = 32,
    ENUM_FIRST_TIME_LEVEL_UP = 64,
    ENUM_FIRST_TIME_GOING_TO_DIE = 128,
    ENUM_FIRST_TIME_UPGRADE_NEXT_GENERATION_WEAPON = 256,
    
};

enum ENUM_SKILL_TYPE
{
    ENUM_SKILL_PLAYER_ATTACK_DAMAGE = 1,
    ENUM_SKILL_HP_REGENERATION = 2,
    ENUM_SKILL_SHOOT_ACCURACY = 3,
    ENUM_SKILL_TELESCOPE = 4,
    ENUM_SKILL_BUILDING_CONCRETE = 5,
    ENUM_SKILL_SKILL_FOCUS = 6,
    ENUM_SKILL_CONSTRUCTION = 7,
    ENUM_SKILL_LEECH_HP = 8,
    ENUM_SKILL_LEECH_MP = 9,
    ENUM_SKILL_WHIRLWIND = 10,
    ENUM_SKILL_BATTLE_EXPERIENCE = 11,
    ENUM_SKILL_EARTH_SPLASH = 12,
    ENUM_SKILL_UPGRADE_LIMIT = 13,
    ENUM_SKILL_LOOT_MONEY = 14,
};

enum ENUM_PLAYER_PERFORM_SKILL_TYPE
{
    ENUM_PLAYER_PERFORM_SKILL_NONE = 0,
    ENUM_PLAYER_PERFORM_SKILL_WHIRLWIND = 1,
    ENUM_PLAYER_PERFORM_SKILL_EARTH_SLASH = 2,
    ENUM_PLAYER_PERFORM_SKILL_RECOVER = 3,
    
};

enum ENUM_MAP_ENVIRONMENT
{
    ENUM_MAP_ENVIRONMENT_NORMAL,
    ENUM_MAP_ENVIRONMENT_UNDERSEA,
    ENUM_MAP_ENVIRONMENT_RAIN,
    ENUM_MAP_ENVIRONMENT_BLOOD_RAIN,
    ENUM_MAP_ENVIRONMENT_SANDY_WIND,
};

enum ENUM_ENVIRONMENT_ANIMATION_TYPE
{
    ENUM_ENVIRONMENT_ANIMATION_MAP101_SEAWAVE1 = 1,
    ENUM_ENVIRONMENT_ANIMATION_MAP101_SEAWAVE2 = 2,
    ENUM_ENVIRONMENT_ANIMATION_MAP101_SEAWAVE3 = 3,
    ENUM_ENVIRONMENT_ANIMATION_MAP101_SEAWAVE4 = 4,
    ENUM_ENVIRONMENT_ANIMATION_MAP101_SUNSHINE = 5,

    ENUM_ENVIRONMENT_ANIMATION_MAP102_RABBIT,
    ENUM_ENVIRONMENT_ANIMATION_MAP102_FLAG,
    
    ENUM_ENVIRONMENT_ANIMATION_MAP105_WATERFALL1,
    ENUM_ENVIRONMENT_ANIMATION_MAP105_WATERFALL2,
    ENUM_ENVIRONMENT_ANIMATION_MAP105_WATERFALL3,
    ENUM_ENVIRONMENT_ANIMATION_MAP105_WAVE1,
    ENUM_ENVIRONMENT_ANIMATION_MAP105_WAVE2,
    ENUM_ENVIRONMENT_ANIMATION_MAP105_WAVE3,
    ENUM_ENVIRONMENT_ANIMATION_MAP105_WAVE4,
    ENUM_ENVIRONMENT_ANIMATION_MAP105_WAVE5,
    
    ENUM_ENVIRONMENT_ANIMATION_MAP106_FOUNTAIN,
    ENUM_ENVIRONMENT_ANIMATION_MAP106_WAVE1,
    ENUM_ENVIRONMENT_ANIMATION_MAP106_WAVE2,
    
    ENUM_ENVIRONMENT_ANIMATION_MAP108_WATERFALL1,
    ENUM_ENVIRONMENT_ANIMATION_MAP108_WATERFALL2,
    ENUM_ENVIRONMENT_ANIMATION_MAP108_WAVE1,
    ENUM_ENVIRONMENT_ANIMATION_MAP108_WAVE2,
    ENUM_ENVIRONMENT_ANIMATION_MAP108_WAVE3,

    
    ENUM_ENVIRONMENT_ANIMATION_MAP109_SEAWEED1,
    ENUM_ENVIRONMENT_ANIMATION_MAP109_SEAWEED2,
    ENUM_ENVIRONMENT_ANIMATION_MAP109_SEAWEED3,
    ENUM_ENVIRONMENT_ANIMATION_MAP109_SEAWEED4,
    ENUM_ENVIRONMENT_ANIMATION_MAP109_SEAWEED5,

    
    ENUM_ENVIRONMENT_ANIMATION_MAP110_LIGHTENING,
    

};

enum ENUM_LANGUAGE
{
    ENUM_LANGUAGE_CHINESE = 0,
    ENUM_LANGUAGE_ENGLISH,
};

enum ENUM_BUFF_STATUS
{
    ENUM_BUFF_STATUS_NORMAL = 0,
    ENUM_BUFF_STATUS_SLOWDOWN = 1,
    ENUM_BUFF_STATUS_POISON = 2,
    ENUM_BUFF_STATUS_DIZZY = 3,
    ENUM_BUFF_STATUS_SPIDER_WEB = 4,
};

enum ENUM_MAGIC_TYPE
{
    ENUM_MAGIC_TYPE_1 = 1,
    ENUM_MAGIC_TYPE_2 = 2,
};

enum ENUM_ENEMY_TYPE
{
    ENUM_ENEMY_TYPE_NORMAL,
    ENUM_ENEMY_TYPE_AIR,
    ENUM_ENEMY_TYPE_BOSS,
    ENUM_ENEMY_TYPE_CHILD,
    ENUM_ENEMY_TYPE_SPECIAL,
};

#endif /* defined(__ike_tdgame__enums__) */
